spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/siamese
    username: siamese
    password: siamese_dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true