name: CI

on:
  push:
  pull_request:

jobs:
  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: siamese
          POSTGRES_USER: siamese
          POSTGRES_PASSWORD: siamese_dev

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U siamese -d siamese"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_URL: jdbc:postgresql://localhost:5432/siamese
      DB_USERNAME: siamese
      DB_PASSWORD: siamese_dev
      MARKET_DATA_API_KEY: test-key
